### ISSUE TITLE
Material UI Bug

### ISSUE THREAD

**Issue by rosekamallove** [CodeFlow201/Team-2#16]
The project won't compile and says: 

    ./src/components/SignUp.js
    Module not found: Can't resolve '@mui/material' in '/home/rosekamallove/Team-2/src/components'

**Comment by rosekamallove** [comment]
Here's and Image 
![image](https://user-images.githubusercontent.com/69139607/137009049-ab45f5f7-ca35-4373-81e5-97cfe1a68d95.png)

**Comment by AJgthb2002** [comment]
@rosekamallove pls check the PR #17
